// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFcXsjMCwlIpNWSaQeVHv1AKqAa0bI3OU',
    appId: '1:181714112197:web:8c49e4730fbf3a12f52aac',
    messagingSenderId: '181714112197',
    projectId: 'courtninjas',
    authDomain: 'courtninjas.firebaseapp.com',
    storageBucket: 'courtninjas.firebasestorage.app',
    measurementId: 'G-E3GVWG2JFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1IfAKfuZUg2joa403Wda8sei_3i89JJI',
    appId: '1:181714112197:android:371a65f3200f86aef52aac',
    messagingSenderId: '181714112197',
    projectId: 'courtninjas',
    storageBucket: 'courtninjas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWF3uJnOBxSaXJcgpWdO4Je-Z_eh_Wznk',
    appId: '1:181714112197:ios:b5a6f0fd760dab8cf52aac',
    messagingSenderId: '181714112197',
    projectId: 'courtninjas',
    storageBucket: 'courtninjas.firebasestorage.app',
    iosClientId: '181714112197-e6fniv073m8u62qnl87l3516rp1ugiaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
